language: node_js
node_js:
  - "8.12.0"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build -- --prod --base-href /ng-cms/

deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep-history: true
  local-dir: dist/ng-cms
  on:
    branch: master
